#!/usr/bin/env bash

if [[ -n $1 ]]; then
    query=$1
else
    read -rp "Query: " query
fi

export query

SCRIPT_PATH=$(dirname "$0")
. "$SCRIPT_PATH/helpers/env"

msg_id=$(mail-query "$query" | $FUZZER | cut -f 4)
[[ -z "$msg_id" ]] && exit
neomutt-show "$msg_id"
