#!/bin/env bash

tmpfile=$(mktemp)

nvim --headless -u NONE -i ~/.local/share/nvim/shada/main.shada -c "redir! > $tmpfile | silent oldfiles | qall!"
grep '^>' ~/.viminfo | cut -c3- | sed 's,~,'"$HOME"',' >> "$tmpfile"

file=$(cut -d' ' -f2 "$tmpfile" | tail -n +2 | awk '!x[$0]++' | $FUZZER)
rm "$tmpfile"

if [ -n "$file" ]; then
    dir=$(dirname "$file")
    urxvtc -cd "$dir" -e nvim "$file"
fi
