#!/usr/bin/env bash

set -e

BW_SESSION_FILE=$HOME/.bw-session
if [ ! -f "$BW_SESSION_FILE" ]; then
    touch "$BW_SESSION_FILE"
    chmod 600 "$BW_SESSION_FILE"
fi

function retrieve() {
    KEY_ID=$(cat "$BW_SESSION_FILE")
    keyctl print "$KEY_ID" | xxd -r -p
}

function store() {
    KEY_ID=$(echo "$1" | keyctl padd user bw-session @u)
    keyctl timeout "$KEY_ID" 900
    echo "$KEY_ID" > "$BW_SESSION_FILE"
}

key=$(retrieve)
if [ -z "$key" ] ; then
    key=$(bw unlock --raw)
    store "$key"
fi
BW_SESSION=$key
export BW_SESSION;

folders_str="$(bw list folders)"
declare -A folders_id2name="($(
  echo "$folders_str" | jq -r '
    .[] as $folder
    | @sh "[\($folder.id)]=\(map(select(.id == $folder.id).name) | join(" "))"
  '
))"

declare -A folders_name2id="($(
  echo "$folders_str" | jq -r '
    .[] as $folder
    | @sh "[\($folder.name)]=\(map(select(.id == $folder.id).id) | join(" "))"
  '
))"

COPY="xsel -t 45000"
logins="$(bw list items)"
entries=$(echo "$logins" | jq -r '.[] | [.name, .folderId] | @tsv')
str=1
readarray -t <<< "$entries"
for entry in "${MAPFILE[@]}"; do
    name=$(echo "$entry" | cut -f1)
    folder_id=$(echo "$entry" | cut -f2)
    if [ -z "$folder_id" ]; then
        printf -v tmp "%s" "$name"
    else
        printf -v tmp "%s/%s" "${folders_id2name[$folder_id]}" "$name"
    fi
    if [[ "$str" == 1 ]]; then
        str="$tmp"
    else
        str+="\n$tmp"
    fi
done

entry="$(echo -e "$str" | sort | $FUZZER)"
entry_folder=$(echo "$entry" | cut -d'/' -f1)
entry_name=$(echo "$entry" | cut -d'/' -f2)
folder_id="${folders_name2id[$entry_folder]}"
selected="$(echo "$logins" | jq -r ".[] | select(.name == \"$entry_name\" and .folderId == \"$folder_id\")")"
printf '%s' "$(echo "$selected" | jq -r '.login.password')" | $COPY
