#!/usr/bin/env bash

entry=$(rbw list --fields folder,name | tr '\t' '/' | sed 's|^/||' | sort | $FUZZER)

part1=$(awk -F/ '{print $1}' <<<"$entry")
part2=$(awk -F/ '{print $2}' <<<"$entry")

COPY="xsel -t 45000"
if [[ -n "$part2" ]]; then
    data=$(rbw get --full --folder "$part1" "$part2")
else
    data=$(rbw get --full "$part1")
fi

NL='
'
case $data in
    *"$NL"*)
        echo "$data" | tail -n +2
        read -r
        echo -n "$(echo "$data" | head -1)" | $COPY
        ;;
    *) echo -n "$data" | $COPY ;;
esac
