#!/usr/bin/env bash

# Fuzzy find Linkding bookmarks
#
# LINKS_FILE is the result from
#   curl -s -H "Authorization: Token $TOKEN" "$HOST/api/bookmarks/" | jq -c '.results'
#
# Where HOST is the uri for the Linkding instance

set -e

LINKS_FILE="${LINKS_FILE:-$1}"

xdg-open "$(jq -r '.[]|[.title,.description,.tag_names,.url]|flatten|@tsv' "$LINKS_FILE" | fzf -e | cut -f 4)"
