#!/usr/bin/env bash

# from passmenu (https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu)
prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/*.gpg "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | $FUZZER)

[[ -n $password ]] || exit

 # can't use --clip since xclip is not working as expected in non-interactive
 # shells
 # (https://unix.stackexchange.com/questions/316715/xclip-works-differently-in-interactive-and-non-interactive-shells)
pass show "$password" | head -n 1 | tr -d '\n' | xsel -t 45000
