#!/usr/bin/env bash

SCRIPT_PATH=$(dirname "$0")
if [ -f "$SCRIPT_PATH/helpers/env" ]; then
    . "$SCRIPT_PATH/helpers/env"
fi

PINBOARD_FILE="${PINBOARD_FILE:-$1}"
PINBOARD_USER="${PINBOARD_USER:-$2}"

url=$(jq -rc '.[]|select(.toread == "yes")' "$PINBOARD_FILE" | shuf | head -n 1 | jq -r '.href|@uri')

xdg-open "https://pinboard.in/search/u:$PINBOARD_USER?query=$url"
